export default {
    $transparent: 'transparent',
    $secondaryBlue: '#325483',
    $bubbles: '#cdebf9',
    $topBar: '#caefe6',
    $white: '#ffffff',
    $black: '#000000',
    $searchFilter: '#ececec',
    $backgroundGrey: '#f6f6f6',
    $alternativeGrey: '#d9d9d9',
    $gradient1: ['#00FBAB', '#0D4EFE'],
    $gradient2: ['#56DDF5', '#D4EFFA'],
    $gradient3: ['#D4EFFA', '#FFFFFF'],
    $text: '#1d232c',
    $textSecondary: '#707070',
    $iconDark: '#5b5b5b',
    $backgroundGray: '#CECECE',
    
    $buttonGreen: '#54E5FF',
    $barPrimaryColor: '#EFFDFF',
    $tabBarBackgroundColor: '#ececec',
    $barPrimaryBoxShadowColor: 'rgba(0, 0, 0, 0.16)',
    $bottomBorderShadowColor: 'rgba(112, 112, 112, 0.1)',
    $containerBorderColor: '#E0E0E0',
    $checkboxBackgroundColor: '#EDF8FD',
    $buttonGray: '#F0F0F0',

}